name: Run Orange Scraper

on:
  schedule:
    - cron: '0 7 * * *'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install -y ./google-chrome-stable_current_amd64.deb

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas selenium webdriver-manager

      - name: Run Python script
        run: python scraper_orange.py

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: output-csv
          path: capacities_prices_bonus_*.csv
          
      - name: Set email subject with date
        id: set-subject
        run: echo "SUBJECT=Bench Orange du $(date +'%d/%m/%Y')" >> $GITHUB_ENV

      - name: Send email with artifact
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          subject: ${{ env.SUBJECT }}
          body: |
            Bonjour à tous,

            Veuillez trouver ci-joint les PVMC des différents forfaits Orange.

            Cordialement,  
            Alexis
          to: laboureyras.alexis2@gmail.com
          from: ${{ secrets.GMAIL_USERNAME }}
          attachments: capacities_prices_bonus_*.csv
          username: ${{ secrets.GMAIL_USERNAME }}
          password: ${{ secrets.GMAIL_APP_PASSWORD }}


