name: Run Colab Notebook

on:
  schedule:
    - cron: '0 7 * * *'  # Exécute tous les jours à 7 heures UTC (9 heures en France en été)
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jupyter pandas gspread gspread-dataframe oauth2client

      - name: Run Colab Notebook
        run: |
          jupyter nbconvert --to notebook --execute Orange25.ipynb --output executed_notebook.ipynb

      - name: List files after execution
        run: |
          ls -la
          pwd

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: output-csv
          path: Orange-Bench-*.csv
          
      - name: Set email subject with date
        id: set-subject
        run: echo "SUBJECT=Bench Orange du $(date +'%d/%m/%Y')" >> $GITHUB_ENV

      - name: Send email with artifact
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          subject: ${{ env.SUBJECT }}
          body: |
            Bonjour à tous,

            Veuillez trouver ci-joint les PVMC des différents forfaits Orange.

            Cordialement,  
            Alexis
          to: laboureyras.alexis2@gmail.com
          from: ${{ secrets.GMAIL_USERNAME }}
          attachments: Orange-Bench-*.csv
          username: ${{ secrets.GMAIL_USERNAME }}
          password: ${{ secrets.GMAIL_APP_PASSWORD }}

