name: Run Colab Notebook

on:
  schedule:
    - cron: '0 6 * * *'  # Exécute tous les jours à 6 heures UTC (8 heures en France en été)
  workflow_dispatch: # Permet de lancer manuellement le workflow

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Utilisez la version Python appropriée

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jupyter pandas gspread gspread-dataframe oauth2client

      - name: Run Colab Notebook
        run: |
          jupyter nbconvert --to notebook --execute Git_Orange_VF2_StableAll.ipynb --output executed_notebook.ipynb

      - name: List files after execution
        run: |
          ls -la
          pwd

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: output-csv
          path: Orange-Bench-*.csv  # Utilisez un joker pour matcher tous les fichiers générés

