name: Run Colab Notebook

on:
  schedule:
    - cron: '0 8 * * *'  # Exécute tous les jours à 8 heures UTC
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Utilisez la version Python appropriée

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install jupyter
        pip install pandas
        pip install gspread
        pip install gspread-dataframe
        pip install oauth2client

    - name: Run Colab Notebook
      run: |
        jupyter nbconvert --to notebook --execute GitOrange_VF2_Stable.ipynb --output executed_notebook.ipynb
